import datetime
from email._policybase import Policy
from inspect import Traceback
from ssl import SSLContext

from .messages import Messages

class Imbox:
    def __init__(
        self,
        hostname: str,
        username: str | None,
        password: str | None,
        ssl: bool,
        port: int | None,
        ssl_context: SSLContext | None,
        policy: Policy | None,
        starttls: bool,
    ): ...
    def __enter__(self) -> Imbox: ...
    def __exit__(self, exc_type: Exception, value: str, traceback: Traceback) -> None: ...
    def logout(self) -> None: ...
    def mark_seen(self, uid: bytes) -> None: ...
    def mark_flag(self, uid: bytes) -> None: ...
    def delete(self, uid: bytes) -> None: ...
    def copy(self, uid: bytes, destination_folder: bytes | str) -> tuple[str, list | list[None, bytes]]: ...
    def move(self, uid: bytes, destination_folder: bytes | str) -> None: ...
    def messages(self, **kwargs: bool | str | datetime.date) -> Messages: ...
    def folders(self) -> tuple[str, list[bytes]]: ...
