import datetime
import io
from collections.abc import KeysView
from email._policybase import Policy
from email.message import Message
from imaplib import IMAP4_SSL

class Struct:
    def __init__(self, **entries: str | datetime.datetime | dict[str, str] | list | list[dict[str, str]]) -> None: ...
    def keys(self) -> KeysView: ...
    def __repr__(self) -> str: ...

def decode_mail_header(value: str, default_charset: str) -> str: ...
def get_mail_addresses(message: Message, header_name: str) -> list[dict[str, str]]: ...
def decode_param(param: str) -> tuple[str, str]: ...
def parse_attachment(message_part: Message) -> dict[str, int | str | io.BytesIO] | None: ...
def decode_content(message: Message) -> str: ...
def fetch_email_by_uid(uid: bytes, connection: IMAP4_SSL, parser_policy: Policy | None) -> Struct: ...
def parse_flags(headers: str) -> list | list[bytes]: ...
def parse_email(raw_email: bytes, policy: Policy | None) -> Struct: ...
